/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kaakaa_hoe' at '15/01/16 22:50' with Gradle 2.0
 *
 * @author kaakaa_hoe, @date 15/01/16 22:50
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
